### ISSUE TITLE
Crash due to small unicode issue

### ISSUE THREAD

**Issue by tushar-deepsource** [matiasb/python-unidiff#102]
Follow these instructions to reproduce:

```console
$ python3 -c 'print("A \342\200\223 B.py")'
A â B.py

$ echo 'hello' > 'A â B.py'

$ git add .

$ git diff --staged
diff --git "a/A \303\242 B.py" "b/A \303\242 B.py"
new file mode 100644
index 0000000..ce01362
--- /dev/null
+++ "b/A \303\242 B.py" 
@@ -0,0 +1 @@
+hello

$ python
```

```python
>>> from unidiff.patch import PatchSet
>>> x = r'''
... diff --git "a/A \303\242 B.py" "b/A \303\242 B.py"
... new file mode 100644
... index 0000000..ce01362
... --- /dev/null
... +++ "b/A \303\242 B.py" 
... @@ -0,0 +1 @@
... +hello
... '''
>>> PatchSet(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tusharsadhwani/code/marvin-test-coverage/venv3/lib/python3.10/site-packages/unidiff/patch.py", line 461, in __init__
    self._parse(data, encoding=encoding, metadata_only=metadata_only)
  File "/Users/tusharsadhwani/code/marvin-test-coverage/venv3/lib/python3.10/site-packages/unidiff/patch.py", line 531, in _parse
    raise UnidiffParseError('Target without source: %s' % line)
unidiff.errors.UnidiffParseError: Target without source: +++ "b/A \303\242 B.py" 
```

**Comment by augmentmoogi** [comment]
Can this be closed now?
