### ISSUE TITLE
unidiff.errors.UnidiffParseError: Unexpected new file found: new file mode 100644

### ISSUE THREAD

**Issue by cpackham-atlnz** [matiasb/python-unidiff#116]
Somewhere between unidiff 0.7.3 and 0.7.4 (and it is still present in 0.7.5) there seems to have been a problem introduced dealing with git diffs that add new files. I'll try and narrow down a reproduction test case but for now this is the traceback I get from a script using unidiff-0.7.5.

```
Traceback (most recent call last):
  File "/usr/local/bin/auto-verifier", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/atl_auto_verifier/auto_verifier.py", line 770, in main
    rc = run_checks(checks[name], args.commitish)
  File "/usr/local/lib/python3.9/site-packages/atl_auto_verifier/auto_verifier.py", line 690, in run_checks
    if check(commitish):
  File "/usr/local/lib/python3.9/site-packages/atl_auto_verifier/auto_verifier.py", line 117, in __call__
    errorcount, self._checkdiff_error_msgs = checkdiff(diff, maxlength=self.maxlength)
  File "/usr/local/lib/python3.9/site-packages/atl_auto_verifier/checkdiff.py", line 116, in checkdiff
    patch = unidiff.PatchSet(diff, enc)
  File "/usr/local/lib/python3.9/site-packages/unidiff/patch.py", line 462, in __init__
    self._parse(data, encoding=encoding, metadata_only=metadata_only)
  File "/usr/local/lib/python3.9/site-packages/unidiff/patch.py", line 500, in _parse
    raise UnidiffParseError('Unexpected new file found: %s' % line)
unidiff.errors.UnidiffParseError: Unexpected new file found: new file mode 100644
```

**Comment by cpackham-atlnz** [comment]
Actually I think the problem is in our script calling into unidiff. We have code to skip over the `diff --git` line but now that unidiff understands it it actually needs it to figure out the filename.
