### ISSUE TITLE
Attribute encode error for Line class

### ISSUE THREAD

**Issue by smroels** [matiasb/python-unidiff#38]
I'm getting an error when effectively executing repr on a Line object (explicitly or implicitly).
>>> record = patch[0]
>>> hunk1_sl = list(record[0].source_lines())
>>> str(hunk1_sl[0])
' /build/'
>>> repr(hunk1_sl[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/unidiff/patch.py", line 76, in __repr__
  File "build/bdist.linux-x86_64/egg/unidiff/patch.py", line 49, in <lambda>
AttributeError: 'Line' object has no attribute 'encode'
>>> hunk1_sl[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/unidiff/patch.py", line 76, in __repr__
  File "build/bdist.linux-x86_64/egg/unidiff/patch.py", line 49, in <lambda>
AttributeError: 'Line' object has no attribute 'encode'

Should:

`class Line(object):
    def __repr__(self):
        return make_str("<Line: %s>") % make_str(self)
`
Be:

`class Line(object):
    def __repr__(self):
        return make_str("<Line: %s>") % make_str(self.value)
`
Cheers.

**Comment by matiasb** [comment]
It should be fixed now, thanks for the report!
